### ISSUE TITLE
Tag with releases

### ISSUE THREAD

**Issue by daigofuji** [HBRGTech/daisy#11]
Thinking about updating daisy with Pattern Lab 2.0. We should tag the releases. Thinking we should have the first public release (ruby sass version) as 1.0 and libsass version as 1.1.

**Comment by flagster76** [comment]
That sounds good to me.  So would the release with PL2.0 be daisy 1.2 or 2.0?  I'm sort of leaning towards 1.2 so as not to seem like we're trying to keep it in sync with PL version numbers, but on the other hand it's conceived as a packaged PL so it wouldn't exactly be wrong either...

**Comment by daigofuji** [comment]
I don't have strong opinion either way. We should follow http://semver.org/ recommendations.

**Comment by daigofuji** [comment]
Now tagged with 1.0 and 1.1
https://github.com/HBRGTech/daisy/releases
