### ISSUE TITLE
styleguide.html is not being gereated

### ISSUE THREAD

**Issue by SirMaster** [HBRGTech/daisy#14]
Hi,

Great stuff on getting a vagrant box ready to use! Saved allot of time.

I do have a question, in the master branch I see that the public directory is already generated, but the "public/styleguide/styleguide.html" is missing.

Even if I do a generate again with "php core/builder.php -g" I get a message saying "ERROR: the main style guide wasn't written out. make sure public/styleguide exists. can copy core/styleguide"

I can navigate properly to http://daisy.pattern.lab/ and see the page with a nice patternlab navigation bar, but also the message "The requested URL /styleguide/html/styleguide.html was not found on this server."

Am I doing something wrong, bad installation? Should this question go to https://github.com/pattern-lab/patternlab-php?

Many thx for any insight!

**Comment by daigofuji** [comment]
Hi @SirMaster, Thanks for nice comments! My gut reaction is maybe that `styleguide/html/styleguide.html` was not generated right for the first time, and therefore `php core/builder.php -g` command cannot write to file. 

Try 

```
vagrant ssh
// Once inside the VM
touch /vagrant_data/www/public/styleguide/html/styleguide.html
```

I do this hack when I run `grunt shell: patternlab` defined [here](https://github.com/HBRGTech/daisy/blob/master/build/tasks/shell.js).

Let me know if this works! Fingers crossed.
Daigo

**Comment by SirMaster** [comment]
@daigofuji ,

Thx that solved it! 

Such a simple solution! Funny thing is that I did a plain copy of `core/styleguide/html/styleguide.html` to `public/styleguide/html/` just to try to see if that would resolve it. But didn't clue in that I should just use a an empty `styleguide.html`

Thanks again.

**Comment by glyphe** [comment]
I had the same problem and I'm just commenting this for anybody who is not that techy (like myself).

I could not execute the code above, but I just created an empty `styleguide.html` file in the `public/styleguide/html` folder. That did the trick (like SirMaster described).
