### ISSUE TITLE
loaded daisy and vagrant up failed because virtualbox was at the latest version

### ISSUE THREAD

**Issue by adrianjbriscoe** [HBRGTech/daisy#16]
loaded daisy and vagrant up failed because virtualbox was at the latest version 5 with latest extensions

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3

**Comment by kdavisk6** [comment]
What version of Vagrant are you using?  Also, what host operating system are you on?

**Comment by flagster76** [comment]
Thanks for the heads-up, @adrianjbriscoe! Sounds like this could be a known issue between Vagrant and VirtualBox - dealt with something like it recently, too: https://github.com/mitchellh/vagrant/issues/5572

There are other host OS dependent factors, in particular with Windows 10 at this time, hence @kdavisk6's questions.

**Comment by adrianjbriscoe** [comment]
hi  kdavis6
Vagrant 1.4.3
hi flagsters76
Linux compact 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:22:15 UTC 2015 i686 i686 i686 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:   trusty

**Comment by flagster76** [comment]
Thanks, @adrianjbriscoe - have you tried updating Vagrant to 1.7.3 or later?  Per the thread I mentioned earlier on the vagrant dev github, it sounds like Vagrant support for VirtualBox 5.x was only very recently added (in the past 3 weeks).

**Comment by adrianjbriscoe** [comment]
thank you, everyone issue not a daisy one - sorry for this post ( a little new to this virtual world) upgraded vagrant to Vagrant 1.7.4 and virtual-box 5 with latest extensions no problem thank you again Matt spot on resolved

**Comment by flagster76** [comment]
No worries, @adrianjbriscoe!  Glad you got it working, and, if anything, having this discussion here might help others who run into the same thing.  Thanks for posting, and for checking out daisy!

**Comment by adrianjbriscoe** [comment]
No thank you for giving us these great tools to try or use in earnest -
brilliant stuff
Regards Adrian
